name: "Composite Action"
description: "[Test] Composite Action"
  
inputs:
  url:
    required: true
  threshold:
    required: true
  strategy:
    required: true

runs:
  using: "composite"
  steps:
    - name: "[ Desktop ] Running Page Speed Insights"
      uses: jakepartusch/psi-action@v1.2
      id: desktop_page_speed_insigths
      with:
        url: ${{ inputs.url }}
        threshold: ${{ inputs.threshold }}
        strategy: ${{ inputs.strategy }}
        key: ${{ secrets.PSI_APIKEY }}
