name: '[ Development ] Page Seed Insight'

on: 
  push:
    branches:
      - development

jobs:
  Development-Page-Speed-Insight:
    runs-on: ubuntu-latest
    steps:
      - name: "[ Mobile ] Running Page Speed Insights"
        uses: jakepartusch/psi-action@v1.2
        id: mobile_page_speed_insigths
        with:
          url: ${{ secrets.DEVELOPMENT_URL }}
          threshold: 90
          strategy: mobile
          key: ${{ secrets.PSI_APIKEY }}

      - name: "[ Desktop ] Running Page Speed Insights"
        uses: jakepartusch/psi-action@v1.2
        id: desktop_page_speed_insigths
        with:
          url: ${{ secrets.DEVELOPMENT_URL }}
          threshold: 90
          strategy: desktop
          key: ${{ secrets.PSI_APIKEY }}