name: '[ Production ] Page Seed Insight'

on: 
  push:
    branches:
      - main

#jobs:
#  Main-Page-Speed-Insight:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "[ Mobile ] Running Page Speed Insights"
#        uses: jakepartusch/psi-action@v1.2
#        id: mobile_page_speed_insigths
#        with:
#          url: ${{ secrets.PRODUCTION_URL }}
#          threshold: 90
#          strategy: mobile
#          key: ${{ secrets.PSI_APIKEY }}
#
#      - name: "[ Desktop ] Running Page Speed Insights"
#        uses: jakepartusch/psi-action@v1.2
#        id: desktop_page_speed_insigths
#        with:
#          url: ${{ secrets.PRODUCTION_URL }}
#          threshold: 90
#          strategy: desktop
#          key: ${{ secrets.PSI_APIKEY }}

jobs:
  Main-Page-Speed-Insight:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "[ Mobile ] Running Page Speed Insights"
        uses: ./.github/actions/psi
        with:
          development_url: ${{ secrets.DEVELOPMENT_URL }}
          production_url: ${{ secrets.PRODUCTION_URL }}
          mobile_threshold: 90
          desktop_threshold: 90
          key: ${{ secrets.PSI_APIKEY }}